[logger]
log_level = "INFO"
log_file = "./logs/log.log"
log_trace_on = false
log_prod_on = false

[db]
db_user = "admin"
db_password = "123"
db_database = "go_api"
db_host = "127.0.0.1"
db_port = 3306

[memory]
memory_type="memory"

[rest]
server_host="127.0.0.1"
server_port="5050"

[grpc]
server_host="127.0.0.1"
server_port="5051"