// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BannerRotationClient is the client API for BannerRotation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BannerRotationClient interface {
	AddBanner(ctx context.Context, in *AddBannerRequest, opts ...grpc.CallOption) (*AddBannerResponse, error)
	DeleteBanner(ctx context.Context, in *DeleteBannerRequest, opts ...grpc.CallOption) (*DeleteBannerResponse, error)
	ClickBanner(ctx context.Context, in *ClickBannerRequest, opts ...grpc.CallOption) (*ClickBannerResponse, error)
	ShowBanner(ctx context.Context, in *ShowBannerRequest, opts ...grpc.CallOption) (*ShowBannerResponse, error)
}

type bannerRotationClient struct {
	cc grpc.ClientConnInterface
}

func NewBannerRotationClient(cc grpc.ClientConnInterface) BannerRotationClient {
	return &bannerRotationClient{cc}
}

func (c *bannerRotationClient) AddBanner(ctx context.Context, in *AddBannerRequest, opts ...grpc.CallOption) (*AddBannerResponse, error) {
	out := new(AddBannerResponse)
	err := c.cc.Invoke(ctx, "/bannerRotation.bannerRotation/addBanner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerRotationClient) DeleteBanner(ctx context.Context, in *DeleteBannerRequest, opts ...grpc.CallOption) (*DeleteBannerResponse, error) {
	out := new(DeleteBannerResponse)
	err := c.cc.Invoke(ctx, "/bannerRotation.bannerRotation/deleteBanner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerRotationClient) ClickBanner(ctx context.Context, in *ClickBannerRequest, opts ...grpc.CallOption) (*ClickBannerResponse, error) {
	out := new(ClickBannerResponse)
	err := c.cc.Invoke(ctx, "/bannerRotation.bannerRotation/clickBanner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerRotationClient) ShowBanner(ctx context.Context, in *ShowBannerRequest, opts ...grpc.CallOption) (*ShowBannerResponse, error) {
	out := new(ShowBannerResponse)
	err := c.cc.Invoke(ctx, "/bannerRotation.bannerRotation/showBanner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BannerRotationServer is the server API for BannerRotation service.
// All implementations must embed UnimplementedBannerRotationServer
// for forward compatibility
type BannerRotationServer interface {
	AddBanner(context.Context, *AddBannerRequest) (*AddBannerResponse, error)
	DeleteBanner(context.Context, *DeleteBannerRequest) (*DeleteBannerResponse, error)
	ClickBanner(context.Context, *ClickBannerRequest) (*ClickBannerResponse, error)
	ShowBanner(context.Context, *ShowBannerRequest) (*ShowBannerResponse, error)
	mustEmbedUnimplementedBannerRotationServer()
}

// UnimplementedBannerRotationServer must be embedded to have forward compatible implementations.
type UnimplementedBannerRotationServer struct {
}

func (UnimplementedBannerRotationServer) AddBanner(context.Context, *AddBannerRequest) (*AddBannerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBanner not implemented")
}
func (UnimplementedBannerRotationServer) DeleteBanner(context.Context, *DeleteBannerRequest) (*DeleteBannerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBanner not implemented")
}
func (UnimplementedBannerRotationServer) ClickBanner(context.Context, *ClickBannerRequest) (*ClickBannerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClickBanner not implemented")
}
func (UnimplementedBannerRotationServer) ShowBanner(context.Context, *ShowBannerRequest) (*ShowBannerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowBanner not implemented")
}
func (UnimplementedBannerRotationServer) mustEmbedUnimplementedBannerRotationServer() {}

// UnsafeBannerRotationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BannerRotationServer will
// result in compilation errors.
type UnsafeBannerRotationServer interface {
	mustEmbedUnimplementedBannerRotationServer()
}

func RegisterBannerRotationServer(s grpc.ServiceRegistrar, srv BannerRotationServer) {
	s.RegisterService(&BannerRotation_ServiceDesc, srv)
}

func _BannerRotation_AddBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBannerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerRotationServer).AddBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bannerRotation.bannerRotation/addBanner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerRotationServer).AddBanner(ctx, req.(*AddBannerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BannerRotation_DeleteBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBannerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerRotationServer).DeleteBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bannerRotation.bannerRotation/deleteBanner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerRotationServer).DeleteBanner(ctx, req.(*DeleteBannerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BannerRotation_ClickBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClickBannerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerRotationServer).ClickBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bannerRotation.bannerRotation/clickBanner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerRotationServer).ClickBanner(ctx, req.(*ClickBannerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BannerRotation_ShowBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowBannerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerRotationServer).ShowBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bannerRotation.bannerRotation/showBanner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerRotationServer).ShowBanner(ctx, req.(*ShowBannerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BannerRotation_ServiceDesc is the grpc.ServiceDesc for BannerRotation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BannerRotation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bannerRotation.bannerRotation",
	HandlerType: (*BannerRotationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addBanner",
			Handler:    _BannerRotation_AddBanner_Handler,
		},
		{
			MethodName: "deleteBanner",
			Handler:    _BannerRotation_DeleteBanner_Handler,
		},
		{
			MethodName: "clickBanner",
			Handler:    _BannerRotation_ClickBanner_Handler,
		},
		{
			MethodName: "showBanner",
			Handler:    _BannerRotation_ShowBanner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "BannerRotationService.proto",
}
